/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eps;

import javax.swing.JPanel;

/**
 *
 * @author prash
 */
public class policedashboard extends javax.swing.JFrame {
String uname;
    /**
     * Creates new form
     */
    public policedashboard() {
        initComponents();
    }
     public policedashboard(String name) {
        initComponents();
        uname=name;
        namelable.setText("WELCOME "+ uname.toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        view_comp_police = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        acc_police = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        database_ps = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        feedback_police = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel10 = new javax.swing.JLabel();
        namelable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        view_comp_police.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view_comp_policeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                view_comp_policeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                view_comp_policeMouseExited(evt);
            }
        });
        view_comp_police.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 153, 255));
        jLabel5.setText("View Complaint");
        view_comp_police.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_view_80px.png"))); // NOI18N
        view_comp_police.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        acc_police.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acc_policeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                acc_policeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                acc_policeMouseExited(evt);
            }
        });
        acc_police.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 153, 255));
        jLabel11.setText("Logout");
        jLabel11.setToolTipText("");
        acc_police.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_logout_rounded_up_80px.png"))); // NOI18N
        acc_police.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        database_ps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                database_psMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                database_psMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                database_psMouseExited(evt);
            }
        });
        database_ps.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 153, 255));
        jLabel14.setText("Database of PS");
        database_ps.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_police_80px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        database_ps.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        feedback_police.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedback_policeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                feedback_policeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                feedback_policeMouseExited(evt);
            }
        });
        feedback_police.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 153, 255));
        jLabel17.setText("View Feedback");
        feedback_police.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_feedback_64px.png"))); // NOI18N
        feedback_police.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(acc_police, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(view_comp_police, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(101, 101, 101)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(feedback_police, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(database_ps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view_comp_police, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(database_ps, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(feedback_police, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acc_police, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 590, 370));

        kGradientPanel1.setkEndColor(new java.awt.Color(102, 153, 255));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 255, 153));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("EPS [ E-POLICE SYSTEM ]");
        jLabel10.setToolTipText("");

        namelable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        namelable.setText("WELCOME");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(namelable, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addGap(40, 40, 40)
                .addComponent(namelable, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jPanel3.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void view_comp_policeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_comp_policeMouseEntered
        // TODO add your handling code here:
        setColor(view_comp_police);
    }//GEN-LAST:event_view_comp_policeMouseEntered

    private void view_comp_policeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_comp_policeMouseExited
        // TODO add your handling code here:
        resetColor(view_comp_police);
    }//GEN-LAST:event_view_comp_policeMouseExited

    private void acc_policeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acc_policeMouseEntered
        // TODO add your handling code here:
        setColor(acc_police);
    }//GEN-LAST:event_acc_policeMouseEntered

    private void acc_policeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acc_policeMouseExited
        // TODO add your handling code here:
        resetColor(acc_police);
    }//GEN-LAST:event_acc_policeMouseExited

    private void database_psMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_database_psMouseEntered
        // TODO add your handling code here:
        setColor(database_ps);
    }//GEN-LAST:event_database_psMouseEntered

    private void database_psMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_database_psMouseExited
        // TODO add your handling code here:
        resetColor(database_ps);
    }//GEN-LAST:event_database_psMouseExited

    private void feedback_policeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedback_policeMouseEntered
        // TODO add your handling code here:
        setColor(feedback_police);
    }//GEN-LAST:event_feedback_policeMouseEntered

    private void feedback_policeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedback_policeMouseExited
        // TODO add your handling code here:
        resetColor(feedback_police);
    }//GEN-LAST:event_feedback_policeMouseExited

    private void view_comp_policeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_comp_policeMouseClicked
        // TODO add your handling code here:
         this.toBack();
        view_comp_police ne=new view_comp_police();
        ne.setVisible(true);
        ne.toFront();
        
    }//GEN-LAST:event_view_comp_policeMouseClicked

    private void feedback_policeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedback_policeMouseClicked
        // TODO add your handling code here:
        this.toBack();
        feedback_police ke=new feedback_police();
        ke.setVisible(true);
        ke.toFront();
    }//GEN-LAST:event_feedback_policeMouseClicked

    private void acc_policeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acc_policeMouseClicked
        // TODO add your handling code here:
        dispose();
        first_page fp=new first_page();
        fp.setVisible(true);
        
    }//GEN-LAST:event_acc_policeMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void database_psMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_database_psMouseClicked
        // TODO add your handling code here:
        this.toBack();
        police_database p=new police_database();
        p.setVisible(true);
        p.toFront();
    }//GEN-LAST:event_database_psMouseClicked

    /**
     * @param args the command line arguments
     */
   public void setColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(197, 197, 197));
 }
 
 public void resetColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(240,240,240));
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acc_police;
    private javax.swing.JPanel database_ps;
    private javax.swing.JPanel feedback_police;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel namelable;
    private javax.swing.JPanel view_comp_police;
    // End of variables declaration//GEN-END:variables
}
