/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eps;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author prash
 */
public class police_log extends javax.swing.JFrame {
Connection con=null;
String username="";
String password="";

    /**
     * Creates new form police_log
     */
    public police_log() {
        initComponents();
    }
    public police_log(String uname,String pass) {
        initComponents();
        this.username=uname;
        this.password=pass;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        pol_id_log = new javax.swing.JTextField();
        kButton2 = new keeptoo.KButton();
        kButton1 = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        kGradientPanel1.setkEndColor(new java.awt.Color(102, 153, 255));
        kGradientPanel1.setkGradientFocus(800);
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 255, 153));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Police ID");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 31, 83, 33));

        pol_id_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pol_id_logActionPerformed(evt);
            }
        });
        kGradientPanel1.add(pol_id_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 185, 33));

        kButton2.setText("Login");
        kButton2.setkEndColor(new java.awt.Color(0, 0, 0));
        kButton2.setkHoverEndColor(new java.awt.Color(102, 255, 102));
        kButton2.setkHoverForeGround(new java.awt.Color(51, 0, 0));
        kButton2.setkHoverStartColor(new java.awt.Color(255, 255, 153));
        kButton2.setkStartColor(new java.awt.Color(51, 0, 0));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 117, 95, 24));

        kButton1.setText("Back");
        kButton1.setkEndColor(new java.awt.Color(0, 0, 0));
        kButton1.setkHoverEndColor(new java.awt.Color(102, 255, 102));
        kButton1.setkHoverForeGround(new java.awt.Color(51, 0, 0));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 255, 153));
        kButton1.setkStartColor(new java.awt.Color(51, 0, 0));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 117, 95, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pol_id_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pol_id_logActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pol_id_logActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        login lo=new login();
        lo.setVisible(true);
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
         try{
             String id=pol_id_log.getText().toString();
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/police_login?useSSL=false","root","");
               String sql="select uname,password from police where uname=? and password=? and id=?";
               PreparedStatement pst=con.prepareStatement(sql);
               pst.setString(1,username);
               pst.setString(2,password);
                pst.setString(3,id);
               
               ResultSet rs =pst.executeQuery();
               if(rs.next())
               {
                   JOptionPane.showMessageDialog(null, "you have successfully logged in");
                   dispose();
                   policedashboard po=new policedashboard(username);
                   po.setVisible(true);
               }
               else
               {
                   JOptionPane.showMessageDialog(null, "wrong username or password or id");
               }
               rs.close();
               con.close();
            }
         catch(Exception e)
         {
              JOptionPane.showMessageDialog(null, e.getMessage());
         }
    }//GEN-LAST:event_kButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       
      
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField pol_id_log;
    // End of variables declaration//GEN-END:variables
}
