/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eps;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author prash
 */
public class register extends javax.swing.JFrame {
Connection con=null;
PreparedStatement pst=null;
    
    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        reg_name5 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        reg_uname5 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        reg_mail5 = new javax.swing.JTextField();
        reg_phone5 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        reg_pass5 = new javax.swing.JPasswordField();
        jLabel31 = new javax.swing.JLabel();
        kButton2 = new keeptoo.KButton();
        kButton1 = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(102, 153, 255));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 255, 153));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel32.setText("Register");
        kGradientPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Name");
        kGradientPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 85, 122, 33));

        reg_name5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reg_name5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_name5reg_nameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(reg_name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 85, 212, 33));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setText("User Name");
        jLabel34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kGradientPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 157, 103, 33));

        reg_uname5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reg_uname5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_uname5reg_unameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(reg_uname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 157, 212, 33));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Email");
        kGradientPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 228, 122, 33));

        reg_mail5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reg_mail5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_mail5reg_mailActionPerformed(evt);
            }
        });
        kGradientPanel1.add(reg_mail5, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 228, 212, 33));

        reg_phone5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reg_phone5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_phone5reg_phoneActionPerformed(evt);
            }
        });
        kGradientPanel1.add(reg_phone5, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 296, 212, 33));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Phone");
        kGradientPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 296, 122, 33));

        reg_pass5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kGradientPanel1.add(reg_pass5, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 367, 212, 33));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Password");
        kGradientPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 367, 111, 33));

        kButton2.setText("Cancel");
        kButton2.setkEndColor(new java.awt.Color(0, 0, 0));
        kButton2.setkHoverEndColor(new java.awt.Color(102, 255, 102));
        kButton2.setkHoverForeGround(new java.awt.Color(51, 0, 0));
        kButton2.setkHoverStartColor(new java.awt.Color(255, 255, 153));
        kButton2.setkStartColor(new java.awt.Color(51, 0, 0));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 467, 102, 25));

        kButton1.setText("Submit");
        kButton1.setkEndColor(new java.awt.Color(0, 0, 0));
        kButton1.setkHoverEndColor(new java.awt.Color(102, 255, 102));
        kButton1.setkHoverForeGround(new java.awt.Color(51, 0, 0));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 255, 153));
        kButton1.setkStartColor(new java.awt.Color(51, 0, 0));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 467, 102, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try{
            String query="INSERT INTO `register`(`Name`,`UserName`,`Email`,`Phone`,`password`) VALUES (?,?,?,?,?)";
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/police_login?useSSL=false","root","");
            pst=con.prepareStatement(query);
            pst.setString(1, reg_name5.getText());
            pst.setString(2, reg_uname5.getText());
            pst.setString(3, reg_mail5.getText());
            pst.setString(4, reg_phone5.getText());
            pst.setString(5, reg_pass5.getText());
            pst.executeUpdate();
            dispose();
            JOptionPane.showMessageDialog(null, "Registered Successfully");

            login lo=new login();
            lo.setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        first_page f=new first_page();
        f.setVisible(true);
    }//GEN-LAST:event_kButton2ActionPerformed

    private void reg_phone5reg_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_phone5reg_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_phone5reg_phoneActionPerformed

    private void reg_mail5reg_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_mail5reg_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_mail5reg_mailActionPerformed

    private void reg_uname5reg_unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_uname5reg_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_uname5reg_unameActionPerformed

    private void reg_name5reg_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_name5reg_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_name5reg_nameActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField reg_mail5;
    private javax.swing.JTextField reg_name5;
    private javax.swing.JPasswordField reg_pass5;
    private javax.swing.JTextField reg_phone5;
    private javax.swing.JTextField reg_uname5;
    // End of variables declaration//GEN-END:variables
}
